name: docker

on:
  push:
    branches:
      - "main"

jobs:
  build:
    uses: decentraland/actions/build-quay-main.yml@main
    with:
      service-name: deployments-to-sqs
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
