name: Manual redeploy to environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - prd

jobs:
  manual-redeploy:
    uses: decentraland/actions/.github/workflows/deploy-latest.yml@main
    with:
      service-name: deployments-to-sns
      deployment-environment: ${{ github.event.inputs.environment }}
